((nil . ((projectile-project-compilation-cmd . "haunt build")
         (projectile-project-name . "Yewscion Blog")
         (projectile-project-run-cmd . "haunt serve")
         (projectile-project-install-cmd . "rsync -avzh site/* cdr255.com:/srv/http/yewscion/")
         )))
